Major updates from main dev
- Updating SkillsCatalogData file
- Fixing bug where currency would still be deducted for buying items over the max amount in the inventory shop
- Adding settings UI to see & remote connected remote devices
- Remote logic updates
- Updating remote models
- Having remote buttons set their image data correctly
- Adding image resizing for remote background images
- Adding remote profile hash validation logic
System.NullReferenceException: Object reference not set to an instance of an object.

at MixItUp.WPF.Controls.Dialogs.UserDialogControl.<UserDialogControl_Loaded>d__2.MoveNext() in S:\Code\mixer-mixitup\MixItUp.WPF\Controls\Dialogs\UserDialogControl.xaml.cs:line 53
--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

- Adding owner for MessageCenter class
- Fixing build break for MessageCenter changes
- Updating to 0.4.21.4