Mirroring main dev branch
- Removing dead code
System.NullReferenceException: Object reference not set to an instance of an object.

at MixItUp.WPF.Controls.MainControls.GiveawayControl.<GlobalEvents_OnChatCommandMessageReceived>d__18.MoveNext() in S:\Code\mixer-mixitup\MixItUp.WPF\Controls\MainControls\GiveawayControl.xaml.cs:line 507
--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
- Adding additional error message details for Streamlabs OBS connection failure
- Adding Follower Only role to chat & mixplay moderation
- Fix Stream Deck plugin shutdown to be more graceful
- Fix build break due to logger.
- Adding support for specifying whether a device & profile is for the Streamer
- Adding Remote Profile/Board settings control
- Limiting remote background images to no more than 300 characters
- Updating remote board & folder logic
- Tweaking Remote folder creation logic
- Updating Fortnite drop map
- Changing interactive to MixPlay naming
- Tweaking response text for Threshold Usage Requirement
- Adding branding images
- Large view model logic rework for Remote controls
- More Remote view model updates
- Adding initial view model loading logic
System.Threading.Tasks.TaskCanceledException: A task was canceled.

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MixItUp.WPF.Controls.MainControls.SongRequestControl.<GlobalEvents_OnSongRequestsChangedOccurred>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
- Adding branding
- Update skills database.
- Adding MixPlay control change detection
- Fixing bug with missing color reference for Global Mods
- Updating to 0.4.21.8
- Fixing winner ordering bug with Fly Swatter MixPlay game
- Update StatisticsTracker.cs Fixed misspelling