Mirroring main development branch
System.NullReferenceException: Object reference not set to an instance of an object.

at MixItUp.WPF.Controls.MainControls.SortedUserObservableCollection.<>c__DisplayClass6_0.<Add>b__0() in S:\Code\mixer-mixitup\MixItUp.WPF\Controls\MainControls\ChatControl.xaml.cs:line 49
at MixItUp.Base.Util.SemaphoreSlimExtensions.<WaitAndRelease>d__1`1.MoveNext()

System.ArgumentException: channelName must have a valid value

at Mixer.Base.Util.Validator.ValidateString(String value, String name)
at Mixer.Base.Services.ChannelsService.<GetChannel>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at MixItUp.Base.Util.AsyncRunner.<RunAsync>d__1`1.MoveNext()

- Updating to 0.4.21.6
- Adding space trimming of chat message text
- Adding Global Mod user role
- Adding unique color for Global Mod users